# -*- coding: utf-8 -*-
"""bicycle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zisFQ6DnbsR0-9kh0qZtQctJ2gMMEtut
"""

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd

train = pd.read_csv('/content/drive/MyDrive/bicycle/train.csv')
test = pd.read_csv('/content/drive/MyDrive/bicycle/test.csv')
submission = pd.read_csv('/content/drive/MyDrive/bicycle/submission.csv')

train.info()

train.head()

test.head()

train['id'].unique()



train['hour'].unique()

"""# columns
- id :id
- hour : 시간
- temperature : 기온
- precipitation : 비가 안오면 0, 비가 오면 1
- windspeed : 풍속
- humidity : 습도
- visibility : 시정
- ozone : 오존
- pm10 미세먼지
- pm2.5 미세먼지
<br>
### label
- count : 시간에 따른 따릉이 대여수
"""

train.isnull().sum()

test.isnull().sum()

train['hour_bef_temperature']

train[train['hour']==13]

