# -*- coding: utf-8 -*-
"""Folium.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1juVJwdglM-b-Z2zorFcqOxcy2rfDmbj1
"""

import folium

coord = [35.1559361,129.1364361]
map_osm = folium.Map(location = coord)
map_osm

coord = [35.1559361,129.1364361]
map_osm = folium.Map(location = coord, zoom_start=15)
map_osm

coord = [35.1559361,129.1364361]
map_osm = folium.Map(location = coord, tiles='Stamen Terrain')
map_osm

coord = [35.2335123, 129.0810047]

map_osm = folium.Map(location=coord, zoom_start=12)

folium.Marker(coord, popup='부산대학교', tooltip = '부산대학교 tooltip').add_to(map_osm) # 마커 생성 뒤 지도에 추가해주는 기능

map_osm.save('index.html')

map_osm

map_osm = folium.Map(location=[37.541, 126.986], zoom_start=11)
folium.Marker([37.5796,126.9215], popup='명지대학교', icon=folium.Icon(color='red',icon='home')).add_to(map_osm)
folium.Circle([37.4600, 126.9519], tooltip='서울대학교', radius=3000, color="green").add_to(map_osm)
folium.CircleMarker([37.5662, 126.9386], radius=10, popup='연세대학교',color="black", fill_color="crimson").add_to(map_osm)
map_osm

"""default images: https://getbootstrap.com/docs/3.3/components/
<br>
검색 기능이 없다<br>
fontawesome:https://fontawesome.com/icons?d=gallery
<br>
해당링크의 무료인것만 쓸 수 있음
"""

map_osm = folium.Map(location=[37.541, 126.986], zoom_start=11)
folium.RegularPolygonMarker([37.566345, 126.977893], popup='서울특별시청', fill_color='red',color='red', number_of_sides=3, radius=30, fill_opacity=0.2).add_to(map_osm)
folium.RegularPolygonMarker([37.4600, 126.9519], popup='서울대학교', fill_color='green',color='green', number_of_sides=4, radius=10, fill_opacity=0.2).add_to(map_osm)
folium.RegularPolygonMarker([37.5662, 126.9386], popup='연세대학교',fill_color='blue',color='blue', number_of_sides=6, radius=10).add_to(map_osm)
map_osm

